# Generated by Django 2.1.3 on 2018-11-18 18:23

from django.db import migrations
import easy_thumbnails.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20181118_1801'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='capa',
            field=easy_thumbnails.fields.ThumbnailerImageField(blank=True, upload_to='capa'),
        ),
    ]
